-- Insert realistic e-commerce products data
INSERT INTO catalog_products (external_id, name, description, price, cost_price, original_price, rating, reviews_count, sales_count, stock_quantity, category, subcategory, brand, supplier_name, supplier_id, image_url, profit_margin, competition_score, trend_score, is_winner, is_trending, is_bestseller, currency, availability_status, delivery_time, shipping_cost, tags, attributes, seo_data) VALUES

-- Electronics & Tech
('ALIEXP-001', 'Écouteurs Sans Fil AirPods Pro Clone', 'Écouteurs Bluetooth 5.0 avec réduction de bruit active, autonomie 6h, boîtier de charge USB-C', 24.99, 8.50, 79.99, 4.6, 2847, 1523, 150, 'Électronique', 'Audio', 'TechSound', 'AliExpress Electronics', 'aliexpress', 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500&h=500&fit=crop', 65.98, 8.2, 9.1, true, true, true, 'EUR', 'in_stock', '2-5 jours', 2.99, ARRAY['Bluetooth', 'Sans fil', 'Audio', 'Écouteurs'], '{"noise_cancellation": true, "battery_life": "6h", "color": "blanc"}', '{"title": "Écouteurs Sans Fil - AirPods Pro Clone", "description": "Écouteurs Bluetooth premium avec réduction de bruit"}'),

('ALIEXP-002', 'Chargeur USB-C 65W GaN', 'Chargeur rapide GaN compact, compatible MacBook, iPhone, Android, technologie PD 3.0', 15.99, 5.20, 49.99, 4.4, 1892, 956, 89, 'Électronique', 'Accessoires', 'ChargeTech', 'TechMart Supply', 'aliexpress', 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=500&h=500&fit=crop', 69.23, 7.8, 8.9, true, true, false, 'EUR', 'in_stock', '3-7 jours', 1.99, ARRAY['Chargeur', 'USB-C', 'GaN', 'Rapide'], '{"power": "65W", "ports": 2, "color": "noir"}', '{"title": "Chargeur USB-C 65W GaN - Charge Rapide", "description": "Chargeur compact haute puissance pour tous vos appareils"}'),

-- Fashion & Lifestyle  
('ALIEXP-003', 'Montre Connectée Smartwatch X10', 'Montre intelligente avec suivi santé, GPS, étanche IP68, autonomie 10 jours', 39.99, 12.80, 199.99, 4.3, 3251, 1876, 245, 'Mode & Accessoires', 'Montres', 'WatchPro', 'Smart Accessories Co', 'aliexpress', 'https://images.unsplash.com/photo-1544117519-31a4b719223d?w=500&h=500&fit=crop', 68.80, 8.5, 8.7, true, true, true, 'EUR', 'in_stock', '5-10 jours', 3.99, ARRAY['Smartwatch', 'Fitness', 'GPS', 'Santé'], '{"waterproof": "IP68", "battery_life": "10 jours", "color": "noir"}', '{"title": "Montre Connectée GPS - Suivi Santé", "description": "Smartwatch complète avec toutes les fonctionnalités modernes"}'),

('ALIEXP-004', 'Sac à Dos Gaming RGB LED', 'Sac à dos gaming avec éclairage LED RGB, port USB, compartiment laptop 17", anti-vol', 34.99, 11.20, 89.99, 4.5, 1456, 723, 67, 'Mode & Accessoires', 'Sacs', 'GamerGear', 'Gaming World Store', 'aliexpress', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop', 67.99, 7.2, 8.1, false, true, false, 'EUR', 'in_stock', '4-8 jours', 4.99, ARRAY['Gaming', 'LED', 'Sac à dos', 'Tech'], '{"led_lights": true, "usb_port": true, "laptop_size": "17 pouces"}', '{"title": "Sac à Dos Gaming RGB - Port USB", "description": "Sac gaming premium avec éclairage LED et fonctions tech"}'),

-- Home & Garden
('ALIEXP-005', 'Lampe LED Connectée WiFi', 'Ampoule LED intelligente 16 millions couleurs, contrôle app, compatible Alexa/Google', 12.99, 3.90, 39.99, 4.2, 5678, 2834, 423, 'Maison & Jardin', 'Éclairage', 'SmartLight', 'Home Automation Plus', 'aliexpress', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&h=500&fit=crop', 69.98, 8.9, 9.3, true, true, true, 'EUR', 'in_stock', '2-4 jours', 1.49, ARRAY['LED', 'WiFi', 'Smart Home', 'Alexa'], '{"colors": "16M", "voice_control": true, "app_control": true}', '{"title": "Ampoule LED Connectée WiFi - 16M Couleurs", "description": "Éclairage intelligent pour maison connectée"}'),

('ALIEXP-006', 'Robot Aspirateur 3-en-1', 'Robot aspirateur, serpillière et stérilisateur UV, navigation laser, app mobile', 89.99, 28.80, 299.99, 4.7, 2156, 1078, 134, 'Maison & Jardin', 'Électroménager', 'CleanBot', 'Smart Home Solutions', 'aliexpress', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&h=500&fit=crop', 68.00, 9.1, 9.5, true, true, true, 'EUR', 'in_stock', '7-12 jours', 9.99, ARRAY['Robot', 'Aspirateur', 'Smart', 'Nettoyage'], '{"mapping": "laser", "uv_sterilization": true, "water_tank": "300ml"}', '{"title": "Robot Aspirateur 3-en-1 - Navigation Laser", "description": "Robot intelligent pour un nettoyage complet automatisé"}'),

-- Sports & Fitness
('ALIEXP-007', 'Tapis de Course Pliable 2.5HP', 'Tapis de course électrique pliable, moteur 2.5HP, vitesse 1-16km/h, écran LCD', 299.99, 96.00, 899.99, 4.4, 892, 445, 23, 'Sport & Fitness', 'Cardio', 'FitPro', 'Fitness Equipment Co', 'aliexpress', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&h=500&fit=crop', 68.00, 7.5, 7.8, false, false, true, 'EUR', 'in_stock', '10-15 jours', 29.99, ARRAY['Tapis de course', 'Fitness', 'Électrique', 'Pliable'], '{"motor": "2.5HP", "max_speed": "16km/h", "foldable": true}', '{"title": "Tapis de Course Pliable 2.5HP - Fitness Maison", "description": "Équipement fitness professionnel pour domicile"}'),

-- Beauty & Health
('ALIEXP-008', 'Brosse Nettoyante Visage Sonique', 'Brosse nettoyante électrique sonique, 6 modes, étanche IPX7, rechargeable USB', 21.99, 6.60, 89.99, 4.6, 3421, 1710, 198, 'Beauté & Santé', 'Soins du Visage', 'BeautyTech', 'Beauty Innovation Store', 'aliexpress', 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=500&h=500&fit=crop', 70.00, 8.3, 8.9, true, true, false, 'EUR', 'in_stock', '3-6 jours', 2.99, ARRAY['Beauté', 'Soins', 'Électrique', 'Sonique'], '{"modes": 6, "waterproof": "IPX7", "charging": "USB"}', '{"title": "Brosse Nettoyante Visage Sonique - 6 Modes", "description": "Soin du visage professionnel à domicile"}'),

-- Car & Moto
('ALIEXP-009', 'Dash Cam 4K Ultra HD', 'Caméra de bord 4K, vision nocturne, WiFi, GPS, détection de mouvement, angle 170°', 54.99, 16.50, 179.99, 4.5, 1687, 843, 89, 'Auto & Moto', 'Électronique Auto', 'DriveSecure', 'Car Tech Solutions', 'aliexpress', 'https://images.unsplash.com/photo-1555617981-dac3880eac6b?w=500&h=500&fit=crop', 70.00, 8.7, 8.4, false, true, true, 'EUR', 'in_stock', '4-7 jours', 3.99, ARRAY['Dash Cam', '4K', 'GPS', 'Sécurité'], '{"resolution": "4K", "night_vision": true, "gps": true, "angle": "170°"}', '{"title": "Dash Cam 4K Ultra HD - Vision Nocturne GPS", "description": "Caméra de bord professionnelle haute définition"}'),

-- Kids & Toys
('ALIEXP-010', 'Drone Caméra 4K Débutant', 'Mini drone avec caméra 4K, stabilisateur 3 axes, vol stationnaire, télécommande', 79.99, 24.00, 249.99, 4.3, 2134, 1067, 156, 'Jouets & Enfants', 'Drones', 'SkyTech', 'Drone Master Store', 'aliexpress', 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=500&h=500&fit=crop', 70.00, 8.1, 8.6, false, true, false, 'EUR', 'in_stock', '5-9 jours', 5.99, ARRAY['Drone', '4K', 'Débutant', 'Caméra'], '{"camera": "4K", "stabilizer": "3-axis", "range": "100m"}', '{"title": "Drone Caméra 4K - Débutant Stabilisateur", "description": "Drone facile à utiliser avec caméra professionnelle"}'),

-- Tools & Hardware  
('ALIEXP-011', 'Kit Outils Électriques 20V', 'Perceuse-visseuse sans fil 20V, 50 accessoires, 2 batteries, chargeur rapide', 69.99, 21.00, 199.99, 4.4, 1523, 761, 78, 'Outils & Bricolage', 'Électroportatif', 'PowerTools', 'Professional Tools Co', 'aliexpress', 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=500&h=500&fit=crop', 70.00, 7.9, 7.6, false, false, true, 'EUR', 'in_stock', '6-10 jours', 7.99, ARRAY['Perceuse', 'Sans fil', '20V', 'Kit'], '{"voltage": "20V", "accessories": 50, "batteries": 2}', '{"title": "Kit Perceuse-Visseuse 20V - 50 Accessoires", "description": "Kit complet d''outils professionnels sans fil"}'),

-- Outdoor & Sports
('ALIEXP-012', 'Tente Camping 4 Personnes', 'Tente familiale étanche, montage rapide 2 minutes, double toit, ventilation optimale', 49.99, 15.00, 149.99, 4.2, 987, 493, 67, 'Sport & Loisirs', 'Camping', 'OutdoorPro', 'Adventure Gear Store', 'aliexpress', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=500&h=500&fit=crop', 70.00, 7.3, 7.9, false, false, false, 'EUR', 'in_stock', '5-8 jours', 8.99, ARRAY['Tente', 'Camping', '4 personnes', 'Étanche'], '{"capacity": "4 personnes", "waterproof": true, "setup_time": "2 minutes"}', '{"title": "Tente Camping 4 Personnes - Montage Rapide", "description": "Tente familiale résistante pour aventures outdoor"}');

-- Insert additional winner and trending products
INSERT INTO catalog_products (external_id, name, description, price, cost_price, original_price, rating, reviews_count, sales_count, stock_quantity, category, subcategory, brand, supplier_name, supplier_id, image_url, profit_margin, competition_score, trend_score, is_winner, is_trending, is_bestseller, currency, availability_status, delivery_time, shipping_cost, tags, attributes, seo_data) VALUES

-- More Winner Products
('WINNER-001', 'Projecteur LED Portable 1080P', 'Mini projecteur portable Full HD 1080P, compatible smartphone/laptop, 3000 lumens', 89.99, 27.00, 299.99, 4.8, 4523, 2261, 89, 'Électronique', 'Vidéo', 'ViewMaster', 'Tech Vision Pro', 'techvision', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500&h=500&fit=crop', 70.00, 9.2, 9.8, true, true, true, 'EUR', 'in_stock', '3-5 jours', 4.99, ARRAY['Projecteur', '1080P', 'Portable', 'LED'], '{"resolution": "1080P", "brightness": "3000 lumens", "portable": true}', '{"title": "Projecteur LED Portable 1080P - 3000 Lumens", "description": "Cinéma portable haute définition pour tous vos besoins"}'),

('WINNER-002', 'Clavier Gaming Mécanique RGB', 'Clavier mécanique gaming RGB, switches bleus, anti-ghosting, repose-poignet', 45.99, 13.80, 129.99, 4.7, 2876, 1438, 156, 'Électronique', 'Gaming', 'KeyMaster', 'Gaming Peripherals Co', 'gamingtech', 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&h=500&fit=crop', 70.00, 8.9, 9.4, true, true, true, 'EUR', 'in_stock', '2-4 jours', 3.99, ARRAY['Clavier', 'Gaming', 'Mécanique', 'RGB'], '{"switches": "blue", "rgb": true, "anti_ghosting": true}', '{"title": "Clavier Gaming Mécanique RGB - Switches Bleus", "description": "Clavier gaming professionnel pour performances optimales"}'),

('WINNER-003', 'Enceinte Bluetooth Waterproof 20W', 'Haut-parleur Bluetooth étanche IPX7, basses profondes, autonomie 24h, LED', 29.99, 9.00, 79.99, 4.6, 3567, 1783, 234, 'Électronique', 'Audio', 'SoundWave', 'Audio Excellence Store', 'audioexcellence', 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&h=500&fit=crop', 70.00, 8.5, 9.1, true, true, true, 'EUR', 'in_stock', '2-3 jours', 2.99, ARRAY['Enceinte', 'Bluetooth', 'Étanche', '20W'], '{"power": "20W", "waterproof": "IPX7", "battery": "24h"}', '{"title": "Enceinte Bluetooth 20W Étanche - 24h Autonomie", "description": "Son puissant et qualité premium pour toutes occasions"}');

-- Add some real orders data
INSERT INTO orders (user_id, order_number, status, total_amount, currency, customer_id, tracking_number, notes, shipping_address, billing_address) VALUES
(gen_random_uuid(), 'ORD-2024-001', 'delivered', 89.97, 'EUR', null, 'TRK123456789', 'Livraison rapide demandée', '{"name": "Jean Dupont", "address": "123 Rue de la Paix", "city": "Paris", "postal_code": "75001", "country": "France"}', '{"name": "Jean Dupont", "address": "123 Rue de la Paix", "city": "Paris", "postal_code": "75001", "country": "France"}'),
(gen_random_uuid(), 'ORD-2024-002', 'shipped', 124.98, 'EUR', null, 'TRK987654321', 'Client premium', '{"name": "Marie Martin", "address": "456 Avenue des Champs", "city": "Lyon", "postal_code": "69001", "country": "France"}', '{"name": "Marie Martin", "address": "456 Avenue des Champs", "city": "Lyon", "postal_code": "69001", "country": "France"}'),
(gen_random_uuid(), 'ORD-2024-003', 'processing', 45.99, 'EUR', null, 'TRK456789123', '', '{"name": "Pierre Dubois", "address": "789 Boulevard République", "city": "Marseille", "postal_code": "13001", "country": "France"}', '{"name": "Pierre Dubois", "address": "789 Boulevard République", "city": "Marseille", "postal_code": "13001", "country": "France"}'),
(gen_random_uuid(), 'ORD-2024-004', 'pending', 199.99, 'EUR', null, null, 'Commande urgente', '{"name": "Sophie Leroy", "address": "321 Rue Victor Hugo", "city": "Toulouse", "postal_code": "31000", "country": "France"}', '{"name": "Sophie Leroy", "address": "321 Rue Victor Hugo", "city": "Toulouse", "postal_code": "31000", "country": "France"}');

-- Add customer data
INSERT INTO customers (user_id, name, email, phone, status, total_orders, total_spent, address) VALUES
(gen_random_uuid(), 'Jean Dupont', 'jean.dupont@email.com', '+33123456789', 'active', 3, 267.94, '{"address": "123 Rue de la Paix", "city": "Paris", "postal_code": "75001", "country": "France"}'),
(gen_random_uuid(), 'Marie Martin', 'marie.martin@email.com', '+33234567890', 'active', 5, 521.45, '{"address": "456 Avenue des Champs", "city": "Lyon", "postal_code": "69001", "country": "France"}'),
(gen_random_uuid(), 'Pierre Dubois', 'pierre.dubois@email.com', '+33345678901', 'active', 2, 145.98, '{"address": "789 Boulevard République", "city": "Marseille", "postal_code": "13001", "country": "France"}'),
(gen_random_uuid(), 'Sophie Leroy', 'sophie.leroy@email.com', '+33456789012', 'active', 1, 199.99, '{"address": "321 Rue Victor Hugo", "city": "Toulouse", "postal_code": "31000", "country": "France"}');

-- Create some supplier data  
INSERT INTO suppliers (user_id, name, contact_email, contact_phone, website, country, rating, status, api_endpoint) VALUES
(gen_random_uuid(), 'AliExpress Electronics', 'supplier@aliexpress.com', '+86123456789', 'https://aliexpress.com', 'Chine', 4.5, 'active', 'https://api.aliexpress.com'),
(gen_random_uuid(), 'TechMart Supply', 'contact@techmart.com', '+86234567890', 'https://techmart.com', 'Chine', 4.2, 'active', 'https://api.techmart.com'),
(gen_random_uuid(), 'Smart Accessories Co', 'info@smartaccessories.com', '+86345678901', 'https://smartaccessories.com', 'Chine', 4.3, 'active', 'https://api.smartaccessories.com'),
(gen_random_uuid(), 'Gaming World Store', 'sales@gamingworld.com', '+86456789012', 'https://gamingworld.com', 'Chine', 4.4, 'active', 'https://api.gamingworld.com');