import { lazy } from 'react';

// Unified pages with plan-based features
export const DashboardLazy = lazy(() => import('@/pages/Dashboard'));
export const ImportManagementLazy = lazy(() => import('@/pages/import/ImportManagement'));
export const CatalogueLazy = lazy(() => import('@/pages/Catalogue'));
export const CatalogueRealLazy = lazy(() => import('@/pages/CatalogueReal'));

// Keep existing for compatibility during transition  
export const DashboardUltraProLazy = lazy(() => import('@/pages/Dashboard'));
export const CatalogueUltraProRealLazy = lazy(() => import('@/pages/Catalogue'));
export const CatalogueUltraProAdvancedLazy = lazy(() => import('@/pages/Catalogue'));
export const OrdersLazy = lazy(() => import('@/pages/Orders'));
export const OrdersUltraProRealLazy = lazy(() => import('@/pages/OrdersUltraProReal'));
export const CRMLazy = lazy(() => import('@/pages/CRM'));
export const CRMUltraProRealLazy = lazy(() => import('@/pages/CRMUltraProReal'));
export const CRMProspectsUltraProLazy = lazy(() => import('@/pages/CRMProspectsUltraPro'));
export const TrackingRealLazy = lazy(() => import('@/pages/TrackingReal'));
export const TrackingUltraProLazy = lazy(() => import('@/pages/TrackingUltraPro'));
export const SEOLazy = lazy(() => import('@/pages/SEO'));
export const SEOUltraProLazy = lazy(() => import('@/pages/SEOUltraPro'));
export const MarketingLazy = lazy(() => import('@/pages/Marketing'));
export const MarketingCreateLazy = lazy(() => import('@/pages/MarketingCreate'));
export const MarketingUltraProLazy = lazy(() => import('@/pages/MarketingUltraPro'));
export const MarketingAnalyticsLazy = lazy(() => import('@/pages/MarketingAnalytics'));
export const MarketingAutomationLazy = lazy(() => import('@/pages/MarketingAutomation'));
export const MarketingCalendarPageLazy = lazy(() => import('@/pages/MarketingCalendarPage'));
export const ABTestingPageLazy = lazy(() => import('@/pages/ABTestingPage'));
export const InventoryLazy = lazy(() => import('@/pages/Inventory'));
export const InventoryUltraProRealLazy = lazy(() => import('@/pages/InventoryUltraProReal'));
export const AutomationLazy = lazy(() => import('@/pages/AutomationPage'));
export const AutomationUltraProLazy = lazy(() => import('@/pages/AutomationUltraPro'));
export const AnalyticsLazy = lazy(() => import('@/pages/Analytics'));
export const AnalyticsUltraProLazy = lazy(() => import('@/pages/AnalyticsUltraPro'));
export const ReviewsLazy = lazy(() => import('@/pages/Reviews'));
export const ReviewsUltraProLazy = lazy(() => import('@/pages/ReviewsUltraPro'));
export const SecurityLazy = lazy(() => import('@/pages/Security'));
export const SecurityUltraProLazy = lazy(() => import('@/pages/SecurityUltraPro'));
export const SupportLazy = lazy(() => import('@/pages/Support'));
export const SupportUltraProLazy = lazy(() => import('@/pages/SupportUltraPro'));
export const BlogLazy = lazy(() => import('@/pages/Blog'));
export const BlogUltraProLazy = lazy(() => import('@/pages/BlogUltraPro'));
export const PluginsLazy = lazy(() => import('@/pages/Plugins'));
export const PluginsUltraProLazy = lazy(() => import('@/pages/PluginsUltraPro'));
export const MobileLazy = lazy(() => import('@/pages/Mobile'));
export const MobileUltraProLazy = lazy(() => import('@/pages/MobileUltraPro'));
export const ExtensionLazy = lazy(() => import('@/pages/Extension'));
export const ExtensionUltraProLazy = lazy(() => import('@/pages/ExtensionUltraPro'));
export const StockLazy = lazy(() => import('@/pages/Stock'));
export const StockUltraProLazy = lazy(() => import('@/pages/StockUltraPro'));
export const SuppliersLazy = lazy(() => import('@/pages/Suppliers'));
export const SuppliersUltraProLazy = lazy(() => import('@/pages/SuppliersUltraPro'));
export const AdminLazy = lazy(() => import('@/pages/Admin'));
export const PaymentSuccessLazy = lazy(() => import('@/pages/PaymentSuccess'));
export const IntegrationsUltraProLazy = lazy(() => import('@/pages/IntegrationsUltraPro'));
export const AdvancedIntelligencePageLazy = lazy(() => import('@/pages/AdvancedIntelligencePage'));
export const AutomationOptimizationPageLazy = lazy(() => import('@/pages/AutomationOptimizationPage'))
export const AdvancedAnalyticsEnterprisePageLazy = lazy(() => import('@/pages/AdvancedAnalyticsEnterprisePage'))
